### ISSUE TITLE
compactor doesn't work with a 32bit ocaml runtime

### ISSUE THREAD

**Issue by ejgallego** [ppedrot/ocaml-compactor#1]
With a 4.02.3 32bits ocaml we get:

```
ocamldep partition.ml hopcroft.ml analyze.ml dot.ml compact.ml main.ml > .deps
File "analyze.ml", line 502, characters 43-53:
Error: Integer literal exceeds the range of representable integers of type int
Makefile:25: recipe for target 'dep' failed
make: *** [dep] Error 2
```

**Comment by ppedrot** [comment]
I'm not sure I want to fix this one. The algorithm uses arrays for efficiency, and OCaml arrays in 32-bits are too small for the intended purpose here. Can't you use a 64-bit architecture?

**Comment by ejgallego** [comment]
Will a 64 bit compact work on 32bit vo files? If so you can close.

**Comment by ppedrot** [comment]
See my answer on the Coq bugzilla.

**Comment by ejgallego** [comment]
cool thanks!
